name: conventional-commits

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-title:
    name: pr-title
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  commit-messages:
    name: commit-messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install @commitlint/config-conventional

      - name: Validate commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: ./commitlint.config.mjs
          helpURL: https://www.conventionalcommits.org/en/v1.0.0/
          ignoreDependabot: 'true'
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
